@startuml

title __MYORG's Class Diagram__\n

  package test.myorg {
    class HmacOneTimePasswordGenerator {
        - algorithm : String
        - passwordLength : int
        - modDivisor : int
        {static} + DEFAULT_PASSWORD_LENGTH : int
        {static} + HOTP_HMAC_ALGORITHM : String
        + HmacOneTimePasswordGenerator()
        + HmacOneTimePasswordGenerator()
        # HmacOneTimePasswordGenerator()
        + generateOneTimePassword()
        + getPasswordLength()
        + getAlgorithm()
    }
  }
  

  package test.myorg {
    class Login {
        {static} + CONNECTOR_STRING : String
        {static} + CONFIG_FILENAME : String
        - ldapSearchbase : String
        - ldapHostname : String
        - ldapPort : String
        + Login()
        + authenticate()
        {static} + main()
    }
  }
  

  package test.myorg {
    class LoginDialog {
        - tfUsername : JTextField
        - pfPassword : JPasswordField
        - lbUsername : JLabel
        - lbPassword : JLabel
        - btnLogin : JButton
        - btnCancel : JButton
        + LoginDialog()
        + getUsername()
        + getPassword()
    }
  }
  

  class AccessibleJDialog {
      # AccessibleJDialog()
      + getAccessibleName()
      + getAccessibleStateSet()
  }
  

  class AccessibleContainerHandler {
      # AccessibleContainerHandler()
      + componentAdded()
      + componentRemoved()
  }
  

  class AccessibleAWTComponentHandler {
      # AccessibleAWTComponentHandler()
      + componentHidden()
      + componentShown()
      + componentMoved()
      + componentResized()
  }
  

  class AccessibleAWTFocusHandler {
      # AccessibleAWTFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  class AccessibleAWTDialog {
      {static} - serialVersionUID : long
      # AccessibleAWTDialog()
      + getAccessibleRole()
      + getAccessibleStateSet()
  }
  

  class AccessibleContainerHandler {
      # AccessibleContainerHandler()
      + componentAdded()
      + componentRemoved()
  }
  

  class AccessibleAWTComponentHandler {
      # AccessibleAWTComponentHandler()
      + componentHidden()
      + componentShown()
      + componentMoved()
      + componentResized()
  }
  

  class AccessibleAWTFocusHandler {
      # AccessibleAWTFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  enum ModalExclusionType {
    NO_EXCLUDE
    APPLICATION_EXCLUDE
    TOOLKIT_EXCLUDE
  }
  

  enum ModalityType {
    MODELESS
    DOCUMENT_MODAL
    APPLICATION_MODAL
    TOOLKIT_MODAL
  }
  

  class AccessibleAWTWindow {
      {static} - serialVersionUID : long
      # AccessibleAWTWindow()
      + getAccessibleRole()
      + getAccessibleStateSet()
  }
  

  class AccessibleContainerHandler {
      # AccessibleContainerHandler()
      + componentAdded()
      + componentRemoved()
  }
  

  class AccessibleAWTComponentHandler {
      # AccessibleAWTComponentHandler()
      + componentHidden()
      + componentShown()
      + componentMoved()
      + componentResized()
  }
  

  class AccessibleAWTFocusHandler {
      # AccessibleAWTFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  enum Type {
    NORMAL
    UTILITY
    POPUP
  }
  

  class WindowDisposerRecord {
      ~ owner : WeakReference<Window>
      ~ weakThis : WeakReference<Window>
      ~ context : WeakReference<AppContext>
      ~ WindowDisposerRecord()
      + updateOwner()
      + dispose()
  }
  

  class AccessibleAWTContainer {
      {static} - serialVersionUID : long
      - propertyListenersCount : int
      # accessibleContainerHandler : ContainerListener
      # AccessibleAWTContainer()
      + getAccessibleChildrenCount()
      + getAccessibleChild()
      + getAccessibleAt()
      + addPropertyChangeListener()
      + removePropertyChangeListener()
  }
  

  class AccessibleContainerHandler {
      # AccessibleContainerHandler()
      + componentAdded()
      + componentRemoved()
  }
  

  class AccessibleAWTComponentHandler {
      # AccessibleAWTComponentHandler()
      + componentHidden()
      + componentShown()
      + componentMoved()
      + componentResized()
  }
  

  class AccessibleAWTFocusHandler {
      # AccessibleAWTFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  class DropTargetEventTargetFilter {
      {static} ~ FILTER : EventTargetFilter
      - DropTargetEventTargetFilter()
      + accept()
  }
  

  interface EventTargetFilter {
      {abstract} + accept()
  }
  

  class MouseEventTargetFilter {
      {static} ~ FILTER : EventTargetFilter
      - MouseEventTargetFilter()
      + accept()
  }
  

  class WakingRunnable {
      ~ WakingRunnable()
      + run()
  }
  

  class AWTTreeLock {
      ~ AWTTreeLock()
  }
  

  abstract class AccessibleAWTComponent {
      {static} - serialVersionUID : long
      - propertyListenersCount : int
      # accessibleAWTComponentHandler : ComponentListener
      # accessibleAWTFocusHandler : FocusListener
      # AccessibleAWTComponent()
      + addPropertyChangeListener()
      + removePropertyChangeListener()
      + getAccessibleName()
      + getAccessibleDescription()
      + getAccessibleRole()
      + getAccessibleStateSet()
      + getAccessibleParent()
      + getAccessibleIndexInParent()
      + getAccessibleChildrenCount()
      + getAccessibleChild()
      + getLocale()
      + getAccessibleComponent()
      + getBackground()
      + setBackground()
      + getForeground()
      + setForeground()
      + getCursor()
      + setCursor()
      + getFont()
      + setFont()
      + getFontMetrics()
      + isEnabled()
      + setEnabled()
      + isVisible()
      + setVisible()
      + isShowing()
      + contains()
      + getLocationOnScreen()
      + getLocation()
      + setLocation()
      + getBounds()
      + setBounds()
      + getSize()
      + setSize()
      + getAccessibleAt()
      + isFocusTraversable()
      + requestFocus()
      + addFocusListener()
      + removeFocusListener()
  }
  

  class AccessibleAWTComponentHandler {
      # AccessibleAWTComponentHandler()
      + componentHidden()
      + componentShown()
      + componentMoved()
      + componentResized()
  }
  

  class AccessibleAWTFocusHandler {
      # AccessibleAWTFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  enum BaselineResizeBehavior {
    CONSTANT_ASCENT
    CONSTANT_DESCENT
    CENTER_OFFSET
    OTHER
  }
  

  class BltBufferStrategy {
      # caps : BufferCapabilities
      # backBuffers : VolatileImage[]
      # validatedContents : boolean
      # width : int
      # height : int
      - insets : Insets
      # BltBufferStrategy()
      + dispose()
      # createBackBuffers()
      + getCapabilities()
      + getDrawGraphics()
      ~ getBackBuffer()
      + show()
      ~ showSubRegion()
      # revalidate()
      ~ revalidate()
      + contentsLost()
      + contentsRestored()
  }
  

  class BltSubRegionBufferStrategy {
      # BltSubRegionBufferStrategy()
      + show()
      + showIfNotLost()
  }
  

  class DummyRequestFocusController {
      - DummyRequestFocusController()
      + acceptRequestFocus()
  }
  

  class FlipBufferStrategy {
      # numBuffers : int
      # caps : BufferCapabilities
      # drawBuffer : Image
      # drawVBuffer : VolatileImage
      # validatedContents : boolean
      ~ width : int
      ~ height : int
      # FlipBufferStrategy()
      # createBuffers()
      - updateInternalBuffers()
      # getBackBuffer()
      # flip()
      ~ flipSubRegion()
      # destroyBuffers()
      + getCapabilities()
      + getDrawGraphics()
      # revalidate()
      ~ revalidate()
      + contentsLost()
      + contentsRestored()
      + show()
      ~ showSubRegion()
      + dispose()
  }
  

  class FlipSubRegionBufferStrategy {
      # FlipSubRegionBufferStrategy()
      + show()
      + showIfNotLost()
  }
  

  class ProxyCapabilities {
      - orig : BufferCapabilities
      - ProxyCapabilities()
  }
  

  enum VSyncType {
    VSYNC_DEFAULT
    VSYNC_ON
    VSYNC_OFF
    id
  }
  

  class FlipContents {
      {static} - I_UNDEFINED : int
      {static} - I_BACKGROUND : int
      {static} - I_PRIOR : int
      {static} - I_COPIED : int
      {static} - NAMES : String[]
      {static} + UNDEFINED : FlipContents
      {static} + BACKGROUND : FlipContents
      {static} + PRIOR : FlipContents
      {static} + COPIED : FlipContents
      - FlipContents()
  }
  

  class SingleBufferStrategy {
      - caps : BufferCapabilities
      + SingleBufferStrategy()
      + getCapabilities()
      + getDrawGraphics()
      + contentsLost()
      + contentsRestored()
      + show()
  }
  

  package test.myorg {
    class Main {
        {static} + CONNECTOR_STRING : String
        {static} + CONFIG_FILENAME : String
        {static} + main()
    }
  }
  

  package test.myorg {
    class TimeBasedOneTimePasswordGenerator {
        - timeStepMillis : long
        {static} + TOTP_ALGORITHM_HMAC_SHA1 : String
        {static} + TOTP_ALGORITHM_HMAC_SHA256 : String
        {static} + TOTP_ALGORITHM_HMAC_SHA512 : String
        + TimeBasedOneTimePasswordGenerator()
        + TimeBasedOneTimePasswordGenerator()
        + TimeBasedOneTimePasswordGenerator()
        + TimeBasedOneTimePasswordGenerator()
        + generateOneTimePassword()
        + getTimeStep()
    }
  }
  

  LoginDialog -up-|> JDialog
  LoginDialog o-- Login : login
  LoginDialog +-down- AccessibleJDialog
  LoginDialog +-down- AccessibleAWTDialog
  LoginDialog +-down- ModalExclusionType
  LoginDialog +-down- ModalityType
  LoginDialog +-down- AccessibleAWTWindow
  LoginDialog +-down- Type
  LoginDialog +-down- WindowDisposerRecord
  LoginDialog +-down- AccessibleAWTContainer
  LoginDialog +-down- DropTargetEventTargetFilter
  LoginDialog +-down- EventTargetFilter
  LoginDialog +-down- MouseEventTargetFilter
  LoginDialog +-down- WakingRunnable
  LoginDialog +-down- AWTTreeLock
  LoginDialog +-down- AccessibleAWTComponent
  LoginDialog +-down- BaselineResizeBehavior
  LoginDialog +-down- BltBufferStrategy
  LoginDialog +-down- BltSubRegionBufferStrategy
  LoginDialog +-down- DummyRequestFocusController
  LoginDialog +-down- FlipBufferStrategy
  LoginDialog +-down- FlipSubRegionBufferStrategy
  LoginDialog +-down- ProxyCapabilities
  LoginDialog +-down- SingleBufferStrategy
  AccessibleJDialog -up-|> AccessibleAWTDialog
  AccessibleJDialog +-down- AccessibleContainerHandler
  AccessibleJDialog +-down- AccessibleAWTComponentHandler
  AccessibleJDialog +-down- AccessibleAWTFocusHandler
  AccessibleContainerHandler -up-|> ContainerListener
  AccessibleAWTComponentHandler -up-|> ComponentListener
  AccessibleAWTFocusHandler -up-|> FocusListener
  AccessibleAWTDialog -up-|> AccessibleAWTWindow
  AccessibleAWTDialog +-down- AccessibleContainerHandler
  AccessibleAWTDialog +-down- AccessibleAWTComponentHandler
  AccessibleAWTDialog +-down- AccessibleAWTFocusHandler
  AccessibleContainerHandler -up-|> ContainerListener
  AccessibleAWTComponentHandler -up-|> ComponentListener
  AccessibleAWTFocusHandler -up-|> FocusListener
  AccessibleAWTWindow -up-|> AccessibleAWTContainer
  AccessibleAWTWindow +-down- AccessibleContainerHandler
  AccessibleAWTWindow +-down- AccessibleAWTComponentHandler
  AccessibleAWTWindow +-down- AccessibleAWTFocusHandler
  AccessibleContainerHandler -up-|> ContainerListener
  AccessibleAWTComponentHandler -up-|> ComponentListener
  AccessibleAWTFocusHandler -up-|> FocusListener
  WindowDisposerRecord -up-|> DisposerRecord
  AccessibleAWTContainer -up-|> AccessibleAWTComponent
  AccessibleAWTContainer +-down- AccessibleContainerHandler
  AccessibleAWTContainer +-down- AccessibleAWTComponentHandler
  AccessibleAWTContainer +-down- AccessibleAWTFocusHandler
  AccessibleContainerHandler -up-|> ContainerListener
  AccessibleAWTComponentHandler -up-|> ComponentListener
  AccessibleAWTFocusHandler -up-|> FocusListener
  DropTargetEventTargetFilter -up-|> EventTargetFilter
  MouseEventTargetFilter -up-|> EventTargetFilter
  WakingRunnable -up-|> Runnable
  AccessibleAWTComponent -up-|> Serializable
  AccessibleAWTComponent -up-|> AccessibleComponent
  AccessibleAWTComponent -up-|> AccessibleContext
  AccessibleAWTComponent +-down- AccessibleAWTComponentHandler
  AccessibleAWTComponent +-down- AccessibleAWTFocusHandler
  AccessibleAWTComponentHandler -up-|> ComponentListener
  AccessibleAWTFocusHandler -up-|> FocusListener
  BltBufferStrategy -up-|> BufferStrategy
  BltSubRegionBufferStrategy -up-|> SubRegionShowable
  BltSubRegionBufferStrategy -up-|> BltBufferStrategy
  DummyRequestFocusController -up-|> RequestFocusController
  FlipBufferStrategy -up-|> BufferStrategy
  FlipSubRegionBufferStrategy -up-|> SubRegionShowable
  FlipSubRegionBufferStrategy -up-|> FlipBufferStrategy
  ProxyCapabilities -up-|> ExtendedBufferCapabilities
  ProxyCapabilities +-down- VSyncType
  ProxyCapabilities +-down- FlipContents
  FlipContents -up-|> AttributeValue
  SingleBufferStrategy -up-|> BufferStrategy
  TimeBasedOneTimePasswordGenerator -up-|> HmacOneTimePasswordGenerator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
